# Generated by Django 2.1.1 on 2018-09-17 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0017_auto_20180131_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='short',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Only accept lowercase letters, numbers or -', regex='^[a-z]+([a-z0-9]*-?[a-z0-9]+)*$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='short',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='Only accept lowercase letters, numbers or -', regex='^[a-z]+([a-z0-9]*-?[a-z0-9]+)*$')]),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='short',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Only accept lowercase letters, numbers or -', regex='^[a-z]+([a-z0-9]*-?[a-z0-9]+)*$')]),
        ),
        migrations.AlterField(
            model_name='productversion',
            name='version',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Only accept comma separated numbers or any text', regex='^([^0-9].*|([0-9]+(\\.?[0-9]+)*))$')]),
        ),
        migrations.AlterField(
            model_name='release',
            name='short',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Only accept lowercase letters, numbers or -', regex='^[a-z]+([a-z0-9]*-?[a-z0-9]+)*$')]),
        ),
        migrations.AlterField(
            model_name='release',
            name='version',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Only accept comma separated numbers or any text', regex='^([^0-9].*|([0-9]+(\\.?[0-9]+)*))$')]),
        ),
    ]
