# Generated by Django 2.1.1 on 2018-09-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0018_auto_20180131_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'provides'), (2, 'requires'), (3, 'obsoletes'), (4, 'conflicts'), (5, 'recommends'), (6, 'suggests')]),
        ),
        migrations.AlterField(
            model_name='image',
            name='subvariant',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
    ]
