# Generated by Django 2.1.1 on 2018-09-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0009_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(default='module', max_length=100),
        ),
    ]
