# Generated by Django 2.1.1 on 2018-09-17 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kerb_auth', '0007_resourceapiurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 255 characters or fewer. Letters, digits and @/./+/-/_ or / only.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-/]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ or / characters.')], verbose_name='username'),
        ),
    ]
